Aperture Language: aperture::Expr Class Reference
aperture::Expr Class Reference
#include <fluent_api.hpp>
Public Member Functions
Expr ()
Expr (const char *s)
Expr (const std::string &s)
Expr (double n)
Expr (int n)
Expr (secure::ValuePtr v)
std::vector< std::string > get_holes () const
secure::ValuePtr get_value () const
bool has_holes () const
template<typename... Args>
Expr operator() (Args &&... args) const
Expr operator* (const Expr &other) const
Expr & operator*= (const Expr &other)
Expr operator+ (const Expr &other) const
Expr & operator+= (const Expr &other)
Expr operator- () const
Expr operator- (const Expr &other) const
Expr operator/ (const Expr &other) const
Expr operator< (const Expr &other) const
Expr operator== (const Expr &other) const
Expr operator> (const Expr &other) const
std::string to_string () const
Static Public Member Functions
static Expr hole (const std::string &name)
Private Attributes
secure::ValuePtr val
Friends
class Computation
class SecureComputation
Detailed Description
Definition at line 38 of file fluent_api.hpp.
Constructor & Destructor Documentation
Expr() [1/6]
aperture::Expr::Expr () inline
Definition at line 46 of file fluent_api.hpp.
Referenced by hole(), operator()(), operator*(), operator+(), operator-(), operator-(), operator/(), operator<(), operator==(), and operator>().
Expr() [2/6]
aperture::Expr::Expr (double n) inline
Definition at line 47 of file fluent_api.hpp.
Expr() [3/6]
aperture::Expr::Expr (int n) inline
Definition at line 48 of file fluent_api.hpp.
Expr() [4/6]
aperture::Expr::Expr (const std::string & s) inline
Definition at line 49 of file fluent_api.hpp.
Expr() [5/6]
aperture::Expr::Expr (const char * s) inline
Definition at line 50 of file fluent_api.hpp.
Expr() [6/6]
aperture::Expr::Expr (secure::ValuePtr v) inline
Definition at line 51 of file fluent_api.hpp.
Member Function Documentation
get_holes()
std::vector< std::string > aperture::Expr::get_holes () const inline
Definition at line 128 of file fluent_api.hpp.
References val.
Referenced by aperture::Computation::holes(), and aperture::SecureComputation::verify().
get_value()
secure::ValuePtr aperture::Expr::get_value () const inline
Definition at line 118 of file fluent_api.hpp.
References val.
Referenced by aperture::Computation::eval(), aperture::Computation::eval_expr(), aperture::Computation::fill(), aperture::Computation::fill(), aperture::ops::if_then_else(), aperture::ops::lambda(), aperture::ops::lambda(), aperture::ops::let(), aperture::ops::let(), aperture::ops::LambdaBuilder< F >::operator[](), and aperture::Computation::partial_eval().
has_holes()
bool aperture::Expr::has_holes () const inline
Definition at line 121 of file fluent_api.hpp.
References val.
hole()
static Expr aperture::Expr::hole (const std::string & name) inline static
Definition at line 54 of file fluent_api.hpp.
References Expr().
Referenced by aperture::build::hole(), and aperture::Hole< T >::operator Expr().
operator()()
template<typename... Args> Expr aperture::Expr::operator() (Args &&... args) const inline
Definition at line 106 of file fluent_api.hpp.
References Expr(), and val.
operator*()
Expr aperture::Expr::operator* (const Expr & other) const inline
Definition at line 67 of file fluent_api.hpp.
References Expr(), and val.
operator*=()
Expr & aperture::Expr::operator*= (const Expr & other) inline
Definition at line 99 of file fluent_api.hpp.
References val.
operator+()
Expr aperture::Expr::operator+ (const Expr & other) const inline
Definition at line 59 of file fluent_api.hpp.
References Expr(), and val.
operator+=()
Expr & aperture::Expr::operator+= (const Expr & other) inline
Definition at line 94 of file fluent_api.hpp.
References val.
operator-() [1/2]
Expr aperture::Expr::operator- () const inline
Definition at line 76 of file fluent_api.hpp.
References Expr(), and val.
operator-() [2/2]
Expr aperture::Expr::operator- (const Expr & other) const inline
Definition at line 63 of file fluent_api.hpp.
References Expr(), and val.
operator/()
Expr aperture::Expr::operator/ (const Expr & other) const inline
Definition at line 71 of file fluent_api.hpp.
References Expr(), and val.
operator<()
Expr aperture::Expr::operator< (const Expr & other) const inline
Definition at line 85 of file fluent_api.hpp.
References Expr(), and val.
operator==()
Expr aperture::Expr::operator== (const Expr & other) const inline
Definition at line 89 of file fluent_api.hpp.
References Expr(), and val.
operator>()
Expr aperture::Expr::operator> (const Expr & other) const inline
Definition at line 81 of file fluent_api.hpp.
References Expr(), and val.
to_string()
std::string aperture::Expr::to_string () const inline
Definition at line 113 of file fluent_api.hpp.
References val.
Referenced by aperture::operator<<(), aperture::SecureComputation::send_to_server(), and aperture::Computation::to_string().
Friends And Related Symbol Documentation
Computation
friend class Computation friend
Definition at line 41 of file fluent_api.hpp.
SecureComputation
friend class SecureComputation friend
Definition at line 42 of file fluent_api.hpp.
Member Data Documentation
val
secure::ValuePtr aperture::Expr::val private
Definition at line 39 of file fluent_api.hpp.
Referenced by get_holes(), get_value(), has_holes(), operator()(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator/(), operator<(), operator==(), operator>(), and to_string().
The documentation for this class was generated from the following file:
/home/runner/work/aperture/aperture/fluent_api.hpp