Aperture Language: aperture::build Namespace Reference
aperture::build Namespace Reference
Functions
Expr hole (const std::string &name)
Expr num (double n)
Expr sym (const std::string &s)
Expr x ()
Expr y ()
Expr z ()
Function Documentation
hole()
Expr aperture::build::hole (const std::string & name) inline
Definition at line 415 of file fluent_api.hpp.
References aperture::Expr::hole().
Referenced by x(), y(), and z().
num()
Expr aperture::build::num (double n) inline
Definition at line 420 of file fluent_api.hpp.
sym()
Expr aperture::build::sym (const std::string & s) inline
Definition at line 425 of file fluent_api.hpp.
x()
Expr aperture::build::x () inline
Definition at line 430 of file fluent_api.hpp.
References hole().
y()
Expr aperture::build::y () inline
Definition at line 431 of file fluent_api.hpp.
References hole().
z()
Expr aperture::build::z () inline
Definition at line 432 of file fluent_api.hpp.
References hole().