Aperture Language: aperture::Computation Class Reference
aperture::Computation Class Reference
#include <fluent_api.hpp>
Public Member Functions
Computation ()=default
Computation (const Expr &expr)
double eval ()
Expr eval_expr ()
template<typename... Args>
Computation & fill (const std::string &name, double value, Args... args)
Computation & fill (const std::unordered_map< std::string, double > &values)
std::vector< std::string > holes () const
Expr partial_eval ()
std::string to_string () const
Computation & with (const Expr &expr)
Protected Attributes
secure::Evaluator evaluator
Expr expression
Private Member Functions
template<typename... Args>
void fill_impl (std::unordered_map< std::string, secure::ValuePtr > &values, const std::string &name, double value, Args... args)
Detailed Description
Definition at line 244 of file fluent_api.hpp.
Constructor & Destructor Documentation
Computation() [1/2]
aperture::Computation::Computation () default
Computation() [2/2]
aperture::Computation::Computation (const Expr & expr) inline explicit
Definition at line 251 of file fluent_api.hpp.
Member Function Documentation
eval()
double aperture::Computation::eval () inline
Definition at line 260 of file fluent_api.hpp.
References evaluator, expression, and aperture::Expr::get_value().
Referenced by aperture::SecureComputation::secure_compute().
eval_expr()
Expr aperture::Computation::eval_expr () inline
Definition at line 274 of file fluent_api.hpp.
References evaluator, expression, and aperture::Expr::get_value().
fill() [1/2]
template<typename... Args> Computation & aperture::Computation::fill (const std::string & name, double value, Args... args) inline
Definition at line 293 of file fluent_api.hpp.
References evaluator, expression, fill_impl(), and aperture::Expr::get_value().
Referenced by aperture::SecureComputation::secure_compute().
fill() [2/2]
Computation & aperture::Computation::fill (const std::unordered_map< std::string, double > & values) inline
Definition at line 312 of file fluent_api.hpp.
References evaluator, expression, and aperture::Expr::get_value().
fill_impl()
template<typename... Args> void aperture::Computation::fill_impl (std::unordered_map< std::string, secure::ValuePtr > & values, const std::string & name, double value, Args... args) inline private
Definition at line 339 of file fluent_api.hpp.
References fill_impl().
Referenced by fill(), and fill_impl().
holes()
std::vector< std::string > aperture::Computation::holes () const inline
Definition at line 328 of file fluent_api.hpp.
References expression, and aperture::Expr::get_holes().
partial_eval()
Expr aperture::Computation::partial_eval () inline
Definition at line 283 of file fluent_api.hpp.
References evaluator, expression, and aperture::Expr::get_value().
Referenced by aperture::SecureComputation::send_to_server().
to_string()
std::string aperture::Computation::to_string () const inline
Definition at line 333 of file fluent_api.hpp.
References expression, and aperture::Expr::to_string().
with()
Computation & aperture::Computation::with (const Expr & expr) inline
Definition at line 254 of file fluent_api.hpp.
References expression.
Member Data Documentation
evaluator
secure::Evaluator aperture::Computation::evaluator protected
Definition at line 246 of file fluent_api.hpp.
Referenced by eval(), eval_expr(), fill(), fill(), and partial_eval().
expression
Expr aperture::Computation::expression protected
Definition at line 247 of file fluent_api.hpp.
Referenced by eval(), eval_expr(), fill(), fill(), holes(), partial_eval(), aperture::SecureComputation::secure_compute(), aperture::SecureComputation::send_to_server(), to_string(), aperture::SecureComputation::verify(), and with().
The documentation for this class was generated from the following file:
/home/runner/work/aperture/aperture/fluent_api.hpp