Aperture Language: aperture::ops Namespace Reference
aperture::ops Namespace Reference
Classes
class LambdaBuilder
Functions
Expr if_then_else (const Expr &cond, const Expr &then_branch, const Expr &else_branch)
Expr lambda (const std::string &param, std::function< Expr(Expr)> body)
Expr lambda (const std::vector< std::string > &params, std::function< Expr(std::vector< Expr >)> body)
Expr let (const std::string &var, const Expr &value, const Expr &body)
Expr let (const std::vector< std::pair< std::string, Expr > > &bindings, const Expr &body)
Function Documentation
if_then_else()
Expr aperture::ops::if_then_else (const Expr & cond, const Expr & then_branch, const Expr & else_branch) inline
Definition at line 143 of file fluent_api.hpp.
References aperture::Expr::get_value().
lambda() [1/2]
Expr aperture::ops::lambda (const std::string & param, std::function< Expr(Expr)> body) inline
Definition at line 211 of file fluent_api.hpp.
References aperture::Expr::get_value().
lambda() [2/2]
Expr aperture::ops::lambda (const std::vector< std::string > & params, std::function< Expr(std::vector< Expr >)> body) inline
Definition at line 223 of file fluent_api.hpp.
References aperture::Expr::get_value().
let() [1/2]
Expr aperture::ops::let (const std::string & var, const Expr & value, const Expr & body) inline
Definition at line 153 of file fluent_api.hpp.
References aperture::Expr::get_value().
let() [2/2]
Expr aperture::ops::let (const std::vector< std::pair< std::string, Expr > > & bindings, const Expr & body) inline
Definition at line 164 of file fluent_api.hpp.
References aperture::Expr::get_value().